# Generated by Django 2.0.5 on 2018-12-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('myText', models.TextField(default='请在这里输入相关信息', max_length=10000)),
                ('myFile', models.FileField(upload_to='../static')),
            ],
        ),
    ]
