# Generated by Django 2.0.5 on 2018-12-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainDisk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('myText', models.TextField(default='请在这里输入相关信息', max_length=10000)),
                ('myFile', models.FileField(upload_to='../media/')),
            ],
        ),
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('myText', models.TextField(default='请在这里输入相关信息', max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='DataModel',
        ),
    ]
